services:
  bookstack:
    image: solidnerd/bookstack:latest
    container_name: bookstack
    depends_on:
      - bookstack_db
    #ports:
    #  - "8080:8080"
    environment:
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      - GOOGLE_APP_ID=${GOOGLE_APP_ID}
      - GOOGLE_APP_SECRET=${GOOGLE_APP_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - /data/apps/bookstack/storage:/var/www/html/storage
      - /data/apps/bookstack/uploads:/var/www/html/public/uploads
    networks:
      - services
      - bookstack
    restart: unless-stopped

  bookstack_db:
    image: mariadb:10.5
    container_name: bookstack_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /data/apps/bookstack/db:/var/lib/mysql
    networks:
      - bookstack
    restart: unless-stopped

networks:
  services:
    external: true
  bookstack:
    driver: bridge
